// <auto-generated />
using System;
using BTCPayServer.Plugins.Serilog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BTCPayServer.Plugins.Serilog.Migrations
{
    [DbContext(typeof(SerilogPluginDbContext))]
    partial class SerilogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Serilog")
                .HasAnnotation("ProductVersion", "1.0.0.1");

            modelBuilder.Entity("BTCPayServer.Plugins.Serilog.Data.SettingData", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("SerilogSettings");
            });
#pragma warning restore 612, 618
        }
    }
}
